export const locations = [
  {
    name: "Beverly Hills - 90210",
    city: "Beverly Hills",
    zipcode: "90210",
    href: "/beverly-hills-90210",
    image: "/images/beverly-hills-90210.jpg",
  },
  {
    name: "Bel Air (Los Angeles) - 90077",
    city: "Bel Air (Los Angeles)",
    zipcode: "90077",
    href: "/bel-air-los-angeles-90077",
    image: "/images/bel-air-los-angeles-90077.jpg",
  },
  {
    name: "Brentwood (Los Angeles) - 90049",
    city: "Brentwood (Los Angeles)",
    zipcode: "90049",
    href: "/brentwood-los-angeles-90049",
    image: "/images/brentwood-los-angeles-90049.jpg",
  },
  {
    name: "Pacific Palisades - 90272",
    city: "Pacific Palisades",
    zipcode: "90272",
    href: "/pacific-palisades-90272",
    image: "/images/pacific-palisades-90272.jpg",
  },
  {
    name: "Santa Monica (North of Montana) - 90402",
    city: "Santa Monica (North of Montana)",
    zipcode: "90402",
    href: "/santa-monica-north-of-montana-90402",
    image: "/images/santa-monica-north-of-montana-90402.jpg",
  },
  {
    name: "Malibu - 90265",
    city: "Malibu",
    zipcode: "90265",
    href: "/malibu-90265",
    image: "/images/malibu-90265.jpg",
  },
  {
    name: "Calabasas - 91302",
    city: "Calabasas",
    zipcode: "91302",
    href: "/calabasas-91302",
    image: "/images/calabasas-91302.jpg",
  },
  {
    name: "Hidden Hills - 91302",
    city: "Hidden Hills",
    zipcode: "91302",
    href: "/hidden-hills-91302",
    image: "/images/hidden-hills-91302.jpg",
  },
  {
    name: "West Hollywood - 90069",
    city: "West Hollywood",
    zipcode: "90069",
    href: "/west-hollywood-90069",
    image: "/images/west-hollywood-90069.jpg",
  },
  {
    name: "Beverly Grove - 90048",
    city: "Beverly Grove",
    zipcode: "90048",
    href: "/beverly-grove-90048",
    image: "/images/beverly-grove-90048.jpg",
  },
  {
    name: "Hancock Park - 90036",
    city: "Hancock Park",
    zipcode: "90036",
    href: "/hancock-park-90036",
    image: "/images/hancock-park-90036.jpg",
  },
  {
    name: "Holmby Hills - 90024",
    city: "Holmby Hills",
    zipcode: "90024",
    href: "/holmby-hills-90024",
    image: "/images/holmby-hills-90024.jpg",
  },
  {
    name: "Westwood - 90024",
    city: "Westwood",
    zipcode: "90024",
    href: "/westwood-90024",
    image: "/images/westwood-90024.jpg",
  },
  {
    name: "Cheviot Hills - 90064",
    city: "Cheviot Hills",
    zipcode: "90064",
    href: "/cheviot-hills-90064",
    image: "/images/cheviot-hills-90064.jpg",
  },
  {
    name: "Century City - 90067",
    city: "Century City",
    zipcode: "90067",
    href: "/century-city-90067",
    image: "/images/century-city-90067.jpg",
  },
  {
    name: "Marina del Rey - 90292",
    city: "Marina del Rey",
    zipcode: "90292",
    href: "/marina-del-rey-90292",
    image: "/images/marina-del-rey-90292.jpg",
  },
  {
    name: "Venice - 90291",
    city: "Venice",
    zipcode: "90291",
    href: "/venice-90291",
    image: "/images/venice-90291.jpg",
  },
  {
    name: "Playa Vista - 90094",
    city: "Playa Vista",
    zipcode: "90094",
    href: "/playa-vista-90094",
    image: "/images/playa-vista-90094.jpg",
  },
  {
    name: "Playa del Rey - 90293",
    city: "Playa del Rey",
    zipcode: "90293",
    href: "/playa-del-rey-90293",
    image: "/images/playa-del-rey-90293.jpg",
  },
  {
    name: "Manhattan Beach - 90266",
    city: "Manhattan Beach",
    zipcode: "90266",
    href: "/manhattan-beach-90266",
    image: "/images/manhattan-beach-90266.jpg",
  },
  {
    name: "Hermosa Beach - 90254",
    city: "Hermosa Beach",
    zipcode: "90254",
    href: "/hermosa-beach-90254",
    image: "/images/hermosa-beach-90254.jpg",
  },
  {
    name: "Redondo Beach (South) - 90277",
    city: "Redondo Beach (South)",
    zipcode: "90277",
    href: "/redondo-beach-south-90277",
    image: "/images/redondo-beach-south-90277.jpg",
  },
  {
    name: "Palos Verdes Estates - 90274",
    city: "Palos Verdes Estates",
    zipcode: "90274",
    href: "/palos-verdes-estates-90274",
    image: "/images/palos-verdes-estates-90274.jpg",
  },
  {
    name: "Rolling Hills - 90274",
    city: "Rolling Hills",
    zipcode: "90274",
    href: "/rolling-hills-90274",
    image: "/images/rolling-hills-90274.jpg",
  },
  {
    name: "Rancho Palos Verdes - 90275",
    city: "Rancho Palos Verdes",
    zipcode: "90275",
    href: "/rancho-palos-verdes-90275",
    image: "/images/rancho-palos-verdes-90275.jpg",
  },
  {
    name: "San Marino - 91108",
    city: "San Marino",
    zipcode: "91108",
    href: "/san-marino-91108",
    image: "/images/san-marino-91108.jpg",
  },
  {
    name: "Pasadena (South Arroyo) - 91105",
    city: "Pasadena (South Arroyo)",
    zipcode: "91105",
    href: "/pasadena-south-arroyo-91105",
    image: "/images/pasadena-south-arroyo-91105.jpg",
  },
  {
    name: "South Pasadena - 91030",
    city: "South Pasadena",
    zipcode: "91030",
    href: "/south-pasadena-91030",
    image: "/images/south-pasadena-91030.jpg",
  },
  {
    name: "La Cañada Flintridge - 91011",
    city: "La Cañada Flintridge",
    zipcode: "91011",
    href: "/la-canada-flintridge-91011",
    image: "/images/la-canada-flintridge-91011.jpg",
  },
  {
    name: "Glendale (Rossmoyne) - 91207",
    city: "Glendale (Rossmoyne)",
    zipcode: "91207",
    href: "/glendale-rossmoyne-91207",
    image: "/images/glendale-rossmoyne-91207.jpg",
  },
  {
    name: "Burbank (Hills) - 91501",
    city: "Burbank (Hills)",
    zipcode: "91501",
    href: "/burbank-hills-91501",
    image: "/images/burbank-hills-91501.jpg",
  },
  {
    name: "Studio City - 91604",
    city: "Studio City",
    zipcode: "91604",
    href: "/studio-city-91604",
    image: "/images/studio-city-91604.jpg",
  },
  {
    name: "Sherman Oaks - 91403",
    city: "Sherman Oaks",
    zipcode: "91403",
    href: "/sherman-oaks-91403",
    image: "/images/sherman-oaks-91403.jpg",
  },
  {
    name: "Encino - 91316",
    city: "Encino",
    zipcode: "91316",
    href: "/encino-91316",
    image: "/images/encino-91316.jpg",
  },
  {
    name: "Tarzana - 91356",
    city: "Tarzana",
    zipcode: "91356",
    href: "/tarzana-91356",
    image: "/images/tarzana-91356.jpg",
  },
  {
    name: "Woodland Hills - 91364",
    city: "Woodland Hills",
    zipcode: "91364",
    href: "/woodland-hills-91364",
    image: "/images/woodland-hills-91364.jpg",
  },
  {
    name: "Porter Ranch - 91326",
    city: "Porter Ranch",
    zipcode: "91326",
    href: "/porter-ranch-91326",
    image: "/images/porter-ranch-91326.jpg",
  },
  {
    name: "Chatsworth - 91311",
    city: "Chatsworth",
    zipcode: "91311",
    href: "/chatsworth-91311",
    image: "/images/chatsworth-91311.jpg",
  },
  {
    name: "Westlake Village - 91361",
    city: "Westlake Village",
    zipcode: "91361",
    href: "/westlake-village-91361",
    image: "/images/westlake-village-91361.jpg",
  },
  {
    name: "Thousand Oaks - 91362",
    city: "Thousand Oaks",
    zipcode: "91362",
    href: "/thousand-oaks-91362",
    image: "/images/thousand-oaks-91362.jpg",
  },
  {
    name: "Agoura Hills - 91301",
    city: "Agoura Hills",
    zipcode: "91301",
    href: "/agoura-hills-91301",
    image: "/images/agoura-hills-91301.jpg",
  },
  {
    name: "Bell Canyon - 91307",
    city: "Bell Canyon",
    zipcode: "91307",
    href: "/bell-canyon-91307",
    image: "/images/bell-canyon-91307.jpg",
  },
  {
    name: "West Hills - 91307",
    city: "West Hills",
    zipcode: "91307",
    href: "/west-hills-91307",
    image: "/images/west-hills-91307.jpg",
  },
  {
    name: "Beverly Glen - 90077",
    city: "Beverly Glen",
    zipcode: "90077",
    href: "/beverly-glen-90077",
    image: "/images/beverly-glen-90077.jpg",
  },
  {
    name: "Mount Olympus (Hollywood Hills) - 90046",
    city: "Mount Olympus (Hollywood Hills)",
    zipcode: "90046",
    href: "/mount-olympus-hollywood-hills-90046",
    image: "/images/mount-olympus-hollywood-hills-90046.jpg",
  },
  {
    name: "Hollywood Hills (East) - 90068",
    city: "Hollywood Hills (East)",
    zipcode: "90068",
    href: "/hollywood-hills-east-90068",
    image: "/images/hollywood-hills-east-90068.jpg",
  },
  {
    name: "Los Feliz - 90027",
    city: "Los Feliz",
    zipcode: "90027",
    href: "/los-feliz-90027",
    image: "/images/los-feliz-90027.jpg",
  },
  {
    name: "Silver Lake - 90039",
    city: "Silver Lake",
    zipcode: "90039",
    href: "/silver-lake-90039",
    image: "/images/silver-lake-90039.jpg",
  },
  {
    name: "Echo Park - 90026",
    city: "Echo Park",
    zipcode: "90026",
    href: "/echo-park-90026",
    image: "/images/echo-park-90026.jpg",
  },
  {
    name: "Culver City (Downtown area) - 90232",
    city: "Culver City (Downtown area)",
    zipcode: "90232",
    href: "/culver-city-downtown-area-90232",
    image: "/images/culver-city-downtown-area-90232.jpg",
  },
  {
    name: "Fisher Island - 33109",
    city: "Fisher Island",
    zipcode: "33109",
    href: "/fisher-island-33109",
    image: "/images/fisher-island-33109.jpg",
  },
  {
    name: "Palm Beach - 33480",
    city: "Palm Beach",
    zipcode: "33480",
    href: "/palm-beach-33480",
    image: "/images/palm-beach-33480.jpg",
  },
  {
    name: "Jupiter Island - 33455",
    city: "Jupiter Island",
    zipcode: "33455",
    href: "/jupiter-island-33455",
    image: "/images/jupiter-island-33455.jpg",
  },
  {
    name: "Palm Beach Gardens - 33418",
    city: "Palm Beach Gardens",
    zipcode: "33418",
    href: "/palm-beach-gardens-33418",
    image: "/images/palm-beach-gardens-33418.jpg",
  },
  {
    name: "Boca Raton - 33432",
    city: "Boca Raton",
    zipcode: "33432",
    href: "/boca-raton-33432",
    image: "/images/boca-raton-33432.jpg",
  },
  {
    name: "Boca Grande - 33921",
    city: "Boca Grande",
    zipcode: "33921",
    href: "/boca-grande-33921",
    image: "/images/boca-grande-33921.jpg",
  },
  {
    name: "Naples - 34102",
    city: "Naples",
    zipcode: "34102",
    href: "/naples-34102",
    image: "/images/naples-34102.jpg",
  },
  {
    name: "Marco Island - 34145",
    city: "Marco Island",
    zipcode: "34145",
    href: "/marco-island-34145",
    image: "/images/marco-island-34145.jpg",
  },
  {
    name: "Longboat Key - 34228",
    city: "Longboat Key",
    zipcode: "34228",
    href: "/longboat-key-34228",
    image: "/images/longboat-key-34228.jpg",
  },
  {
    name: "Siesta Key / Sarasota (North) - 34236",
    city: "Siesta Key / Sarasota (North)",
    zipcode: "34236",
    href: "/siesta-key-sarasota-north-34236",
    image: "/images/siesta-key-sarasota-north-34236.jpg",
  },
  {
    name: "Sarasota (North of State Rd 789 / Bird Key area) - 34236",
    city: "Sarasota (North of State Rd 789 / Bird Key area)",
    zipcode: "34236",
    href: "/sarasota-north-of-state-rd-789-bird-key-area-34236",
    image: "/images/sarasota-north-of-state-rd-789-bird-key-area-34236.jpg",
  },
  {
    name: "Sanibel Island - 33957",
    city: "Sanibel Island",
    zipcode: "33957",
    href: "/sanibel-island-33957",
    image: "/images/sanibel-island-33957.jpg",
  },
  {
    name: "Captiva Island - 33924",
    city: "Captiva Island",
    zipcode: "33924",
    href: "/captiva-island-33924",
    image: "/images/captiva-island-33924.jpg",
  },
  {
    name: "Key Biscayne - 33149",
    city: "Key Biscayne",
    zipcode: "33149",
    href: "/key-biscayne-33149",
    image: "/images/key-biscayne-33149.jpg",
  },
  {
    name: "Coral Gables - 33146",
    city: "Coral Gables",
    zipcode: "33146",
    href: "/coral-gables-33146",
    image: "/images/coral-gables-33146.jpg",
  },
  {
    name: "Miami Beach (South Beach / Mid Beach) - 33139 / 33140",
    city: "Miami Beach (South Beach / Mid Beach)",
    zipcode: "33139 / 33140",
    href: "/miami-beach-south-beach-mid-beach-33139-33140",
    image: "/images/miami-beach-south-beach-mid-beach-33139-33140.jpg",
  },
  {
    name: "Bal Harbour - 33154",
    city: "Bal Harbour",
    zipcode: "33154",
    href: "/bal-harbour-33154",
    image: "/images/bal-harbour-33154.jpg",
  },
  {
    name: "Surfside - 33154",
    city: "Surfside",
    zipcode: "33154",
    href: "/surfside-33154",
    image: "/images/surfside-33154.jpg",
  },
  {
    name: "Sunny Isles Beach - 33160",
    city: "Sunny Isles Beach",
    zipcode: "33160",
    href: "/sunny-isles-beach-33160",
    image: "/images/sunny-isles-beach-33160.jpg",
  },
  {
    name: "West Palm Beach (Elmwood / Historic District pockets) - 33401",
    city: "West Palm Beach (Elmwood / Historic District pockets)",
    zipcode: "33401",
    href: "/west-palm-beach-elmwood-historic-district-pockets-33401",
    image:
      "/images/west-palm-beach-elmwood-historic-district-pockets-33401.jpg",
  },
  {
    name: "Palm Coast / Hammock (select upscale pockets) - 32137",
    city: "Palm Coast / Hammock (select upscale pockets)",
    zipcode: "32137",
    href: "/palm-coast-hammock-select-upscale-pockets-32137",
    image: "/images/palm-coast-hammock-select-upscale-pockets-32137.jpg",
  },
  {
    name: "Vero Beach - 32963",
    city: "Vero Beach",
    zipcode: "32963",
    href: "/vero-beach-32963",
    image: "/images/vero-beach-32963.jpg",
  },
  {
    name: "Fort Lauderdale (Las Olas / Harbor Beach) - 33301 / 33308",
    city: "Fort Lauderdale (Las Olas / Harbor Beach)",
    zipcode: "33301 / 33308",
    href: "/fort-lauderdale-las-olas-harbor-beach-33301-33308",
    image: "/images/fort-lauderdale-las-olas-harbor-beach-33301-33308.jpg",
  },
  {
    name: "Boca Raton - (Royal Palm / Mizner Park area) - 33432",
    city: "Boca Raton",
    zipcode: "33432",
    href: "/boca-raton-royal-palm-mizner-park-area-33432",
    image: "/images/boca-raton-royal-palm-mizner-park-area-33432.jpg",
  },
  {
    name: "Highland Beach - 33487",
    city: "Highland Beach",
    zipcode: "33487",
    href: "/highland-beach-33487",
    image: "/images/highland-beach-33487.jpg",
  },
  {
    name: "Delray Beach (East / Lake Ida area) - 33483",
    city: "Delray Beach (East / Lake Ida area)",
    zipcode: "33483",
    href: "/delray-beach-east-lake-ida-area-33483",
    image: "/images/delray-beach-east-lake-ida-area-33483.jpg",
  },
  {
    name: "Boca Raton - (Estates & Country Club pockets) - 33486",
    city: "Boca Raton",
    zipcode: "33486",
    href: "/boca-raton-estates-country-club-pockets-33486",
    image: "/images/boca-raton-estates-country-club-pockets-33486.jpg",
  },
  {
    name: "Del Mar/Indian River Shores (Jupiter area) - 33455",
    city: "Del Mar/Indian River Shores (Jupiter area)",
    zipcode: "33455",
    href: "/del-mar-indian-river-shores-jupiter-area-33455",
    image: "/images/del-mar-indian-river-shores-jupiter-area-33455.jpg",
  },
  {
    name: "Palm Shores / Viera (select high-end pockets) - 32940",
    city: "Palm Shores / Viera (select high-end pockets)",
    zipcode: "32940",
    href: "/palm-shores-viera-select-high-end-pockets-32940",
    image: "/images/palm-shores-viera-select-high-end-pockets-32940.jpg",
  },
  {
    name: "Indian River / Orchid Island (Vero/Indian River County) - 32963",
    city: "Indian River / Orchid Island (Vero/Indian River County)",
    zipcode: "32963",
    href: "/indian-river-orchid-island-vero-indian-river-county-32963",
    image:
      "/images/indian-river-orchid-island-vero-indian-river-county-32963.jpg",
  },
  {
    name: "St. Augustine (historic/coastal higher-end pockets) - 32080",
    city: "St. Augustine (historic/coastal higher-end pockets)",
    zipcode: "32080",
    href: "/st-augustine-historic-coastal-higher-end-pockets-32080",
    image: "/images/st-augustine-historic-coastal-higher-end-pockets-32080.jpg",
  },
  {
    name: "Mount Dora (Lakefront luxury pockets) - 32757",
    city: "Mount Dora (Lakefront luxury pockets)",
    zipcode: "32757",
    href: "/mount-dora-lakefront-luxury-pockets-32757",
    image: "/images/mount-dora-lakefront-luxury-pockets-32757.jpg",
  },
  {
    name: "Naples (Aqualane Shores / Old Naples) - 34102",
    city: "Naples (Aqualane Shores / Old Naples)",
    zipcode: "34102",
    href: "/naples-aqualane-shores-old-naples-34102",
    image: "/images/naples-aqualane-shores-old-naples-34102.jpg",
  },
  {
    name: "Bonita Springs (Estero / Pelican Landing pockets) - 34134",
    city: "Bonita Springs (Estero / Pelican Landing pockets)",
    zipcode: "34134",
    href: "/bonita-springs-estero-pelican-landing-pockets-34134",
    image: "/images/bonita-springs-estero-pelican-landing-pockets-34134.jpg",
  },
  {
    name: "Estero (Miromar Lakes / luxury enclaves) - 33928",
    city: "Estero (Miromar Lakes / luxury enclaves)",
    zipcode: "33928",
    href: "/estero-miromar-lakes-luxury-enclaves-33928",
    image: "/images/estero-miromar-lakes-luxury-enclaves-33928.jpg",
  },
  {
    name: "Venice (Venetian / Nokomis luxury pockets) - 34285",
    city: "Venice (Venetian / Nokomis luxury pockets)",
    zipcode: "34285",
    href: "/venice-venetian-nokomis-luxury-pockets-34285",
    image: "/images/venice-venetian-nokomis-luxury-pockets-34285.jpg",
  },
  {
    name: "Clearwater / Sand Key (beachfront pockets) - 33767",
    city: "Clearwater / Sand Key (beachfront pockets)",
    zipcode: "33767",
    href: "/clearwater-sand-key-beachfront-pockets-33767",
    image: "/images/clearwater-sand-key-beachfront-pockets-33767.jpg",
  },
  {
    name: "St. Petersburg (Old Northeast / Snell Isle) - 33701",
    city: "St. Petersburg (Old Northeast / Snell Isle)",
    zipcode: "33701",
    href: "/st-petersburg-old-northeast-snell-isle-33701",
    image: "/images/st-petersburg-old-northeast-snell-isle-33701.jpg",
  },
  {
    name: "Palm Harbor / Dunedin (beach & golf pockets) - 34684",
    city: "Palm Harbor / Dunedin (beach & golf pockets)",
    zipcode: "34684",
    href: "/palm-harbor-dunedin-beach-golf-pockets-34684",
    image: "/images/palm-harbor-dunedin-beach-golf-pockets-34684.jpg",
  },
  {
    name: "Tampa (Hyde Park / Davis Islands / Beach Park) - 33606",
    city: "Tampa (Hyde Park / Davis Islands / Beach Park)",
    zipcode: "33606",
    href: "/tampa-hyde-park-davis-islands-beach-park-33606",
    image: "/images/tampa-hyde-park-davis-islands-beach-park-33606.jpg",
  },
  {
    name: "River Oaks / Tampa (waterfront estates) - 33609",
    city: "River Oaks / Tampa (waterfront estates)",
    zipcode: "33609",
    href: "/river-oaks-tampa-waterfront-estates-33609",
    image: "/images/river-oaks-tampa-waterfront-estates-33609.jpg",
  },
  {
    name: "Winter Park (Orlando area affluent suburb) - 32789",
    city: "Winter Park (Orlando area affluent suburb)",
    zipcode: "32789",
    href: "/winter-park-orlando-area-affluent-suburb-32789",
    image: "/images/winter-park-orlando-area-affluent-suburb-32789.jpg",
  },
  {
    name: "Windermere (private lake estates) - 34786",
    city: "Windermere (private lake estates)",
    zipcode: "34786",
    href: "/windermere-private-lake-estates-34786",
    image: "/images/windermere-private-lake-estates-34786.jpg",
  },
  {
    name: "Orlando (Lake Nona / Isle of Hope pockets) - 32827",
    city: "Orlando (Lake Nona / Isle of Hope pockets)",
    zipcode: "32827",
    href: "/orlando-lake-nona-isle-of-hope-pockets-32827",
    image: "/images/orlando-lake-nona-isle-of-hope-pockets-32827.jpg",
  },
  {
    name: "Ponte Vedra Beach - 32082",
    city: "Ponte Vedra Beach",
    zipcode: "32082",
    href: "/ponte-vedra-beach-32082",
    image: "/images/ponte-vedra-beach-32082.jpg",
  },
  {
    name: "Amelia Island (Fernandina Beach luxury pockets) - 32034",
    city: "Amelia Island (Fernandina Beach luxury pockets)",
    zipcode: "32034",
    href: "/amelia-island-fernandina-beach-luxury-pockets-32034",
    image: "/images/amelia-island-fernandina-beach-luxury-pockets-32034.jpg",
  },
  {
    name: "Key West - 33040",
    city: "Key West",
    zipcode: "33040",
    href: "/key-west-33040",
    image: "/images/key-west-33040.jpg",
  },
  {
    name: "Islamorada - 33036",
    city: "Islamorada",
    zipcode: "33036",
    href: "/islamorada-33036",
    image: "/images/islamorada-33036.jpg",
  },
  {
    name: "Naples (Vanderbilt Beach / Park Shore) - 34103",
    city: "Naples (Vanderbilt Beach / Park Shore)",
    zipcode: "34103",
    href: "/naples-vanderbilt-beach-park-shore-34103",
    image: "/images/naples-vanderbilt-beach-park-shore-34103.jpg",
  },
  {
    name: "Boca Raton / Gulfstream (coastal estates) - 33432",
    city: "Boca Raton / Gulfstream (coastal estates)",
    zipcode: "33432",
    href: "/boca-raton-gulfstream-coastal-estates-33432",
    image: "/images/boca-raton-gulfstream-coastal-estates-33432.jpg",
  },
];
